name       : kcontacts
version    : 5.80.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.80/kcontacts-5.80.0.tar.xz : d387b909e2e52b35efef6201502cb71705a76fdcd4fda8e7e535e5c66cbf7b9c
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
rundeps    :
    - kcodecs
    - devel :
        - kcodecs-devel
        - kconfig-devel
        - kcoreaddons-devel
        - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
