name       : kcontacts
version    : 18.08.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kcontacts-18.08.2.tar.xz : 628b5640f8a404e96913b647c01c30a9fbe3421d03c3ddd8ef5002d35090967c
license    : LGPL-2.1
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
