name       : kcontacts
version    : 5.72.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kcontacts-5.72.0.tar.xz : adec7528f13bcf3015d9604204cf7642e891c0be79b72aa10fd13f0a237c5d8d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
