name       : kcontacts
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kcontacts-17.04.0.tar.xz : 30bfc01174075bff8500d543b8082dfad96289a89cd271bff6d86fa4c46caa98
license    : LGPL-2.1
component  : desktop.library
summary    :  KCodecs provide a collection of methods to manipulate strings using various encodings.
description: |
    KCodecs provide a collection of methods to manipulate strings using various encodings.
builddeps  :
    - pkgconfig(glu)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
