name       : kcontacts
version    : 5.92.0
release    : 55
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/kcontacts-5.92.0.tar.xz : 1276006e50f507216a8241ca4b26b02c67c42e5bee26a6b391db6ae4f72533ce
homepage   : https://community.kde.org/Frameworks
license    :
    - BSD-3-Clause
    - LGPL-2.0-or-later
    - MIT
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
rundeps    :
    - kcodecs
    - devel :
        - kcodecs-devel
        - kconfig-devel
        - kcoreaddons-devel
        - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
