name       : kcontacts
version    : 5.66.0
release    : 30
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/kcontacts-5.66.0.tar.xz : 08086f554eb4718e91a9e96d143ba05fc741289928db9bcc21b21ca7125b0017
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
