name       : kcontacts
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kcontacts-17.12.1.tar.xz : 93ff27692120eff468d345f91f22897bdc2b46ea06bae6eb8b9928efe14a4a94
license    : LGPL-2.1
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
