name       : kcontacts
version    : 5.67.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcontacts-5.67.0.tar.xz : 15b09c7cc086f535dfc7d9583ac84ace890f7da64982945ce789c09ff6e0ef83
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Address book API for KDE
description: |
    KContacts provides an API for address book data. This can be used by all applications using data of this type.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
